### ISSUE TITLE
file to patch :

### ISSUE THREAD

**Issue by ahmedelsheikh** [qrush/unix#1]
while make unix directory i got this prompt

missing header for unified diff at line 3 of patch
The text leading up to this was:
--------------------------
|--- init.clean	2008-06-25 08:39:57.000000000 -1000
|+++ init.s	2008-06-25 08:40:08.000000000 -1000
--------------------------
File to patch:

**Comment by qrush** [comment]
Closing all these as this is just an import/historical repo.
