### ISSUE TITLE
The /images directory not created on "make" command.

### ISSUE THREAD

**Issue by akashchgupta** [qrush/unix#4]
When I did a "make" on the top level of the directory the /images directory was not created.
Here is the make command output.

root@AKASH:~/Desktop/unix-master# make
(cd tools; make)
make[1]: Entering directory '/root/Desktop/unix-master/tools'
cc -g -Wall    mkfs.c   -o mkfs
mkfs.c: In function ‘write_superblock’:
mkfs.c:131:52: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
   if (debug) printf("Writing %d inodes, each size %d, total %d\n",
                                                   ~^
                                                   %ld
mkfs.c:131:62: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
   if (debug) printf("Writing %d inodes, each size %d, total %d\n",
                                                             ~^
                                                             %ld
     icount, sizeof(struct v1inode), icount * sizeof(struct v1inode));
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mkfs.c: In function ‘write_dir’:
mkfs.c:364:35: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
     printf("Writing dir %s, size %d, %d blks from block %d (offset 0x%x) on\n",
                                  ~^
                                  %ld
     name, d->numentries * sizeof(struct v1dirent),
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mkfs.c:364:39: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘long unsigned int’ [-Wformat=]
     printf("Writing dir %s, size %d, %d blks from block %d (offset 0x%x) on\n",
                                      ~^
                                      %ld
mkfs.c: In function ‘main’:
mkfs.c:686:7: warning: variable ‘fs_size’ set but not used [-Wunused-but-set-variable]
   int fs_size;   /* Equal to disksize minus any swap */
       ^~~~~~~
cc -g -Wall    ml.c   -o ml
(cd apout; make; rm *.o)
make[2]: Entering directory '/root/Desktop/unix-master/tools/apout'
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o aout.o aout.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o branch.o branch.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o bsd_ioctl.o bsd_ioctl.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o bsd_signal.o bsd_signal.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o bsdtrap.o bsdtrap.c
bsdtrap.c: In function ‘bsdtrap’:
bsdtrap.c:60:11: warning: variable ‘fmode’ set but not used [-Wunused-but-set-variable]
     char *fmode;    /* used with fdopen only */
           ^~~~~
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o cpu.o cpu.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o debug.o debug.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o double.o double.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o ea.o ea.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o fp.o fp.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o itab.o itab.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o ke11a.o ke11a.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o magic.o magic.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o main.o main.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o single.o single.c
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o v1trap.o v1trap.c
v1trap.c: In function ‘v1trap’:
v1trap.c:78:9: warning: variable ‘fmode’ set but not used [-Wunused-but-set-variable]
   char *fmode;   /* used with fdopen only */
         ^~~~~
gcc -Wall -g -DEMU211 -DEMUV1 -DNATIVES -DRUN_V1_RAW -DDEBUG -DZERO_MEMORY -DWRITEBASE   -c -o v7trap.o v7trap.c
v7trap.c: In function ‘v7trap’:
v7trap.c:73:11: warning: variable ‘fmode’ set but not used [-Wunused-but-set-variable]
     char *fmode;  /* used with fdopen only */
           ^~~~~
v7trap.c: In function ‘v7signal’:
v7trap.c:695:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       return((int)signal(v7sig[sig], SIG_IGN));
              ^
v7trap.c:697:14: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
       return((int)signal(v7sig[sig], SIG_DFL));
              ^
v7trap.c: In function ‘v7trap’:
v7trap.c:164:5: warning: ‘larg’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  tim= larg;
  ~~~^~~~~~
cc -g aout.o branch.o bsd_ioctl.o bsd_signal.o bsdtrap.o cpu.o debug.o double.o ea.o fp.o itab.o ke11a.o magic.o main.o single.o v1trap.o v7trap.o -o apout -lm
make[2]: Leaving directory '/root/Desktop/unix-master/tools/apout'
make[1]: Leaving directory '/root/Desktop/unix-master/tools'
(cd build; make install)
make[1]: Entering directory '/root/Desktop/unix-master/build'
Building clean source...
Patching...
  aout407
/bin/sh: 4: patch: not found
  ecore
/bin/sh: 4: patch: not found
  fastout
/bin/sh: 4: patch: not found
  initorig
/bin/sh: 4: patch: not found
  shell
/bin/sh: 4: patch: not found
  shorig
/bin/sh: 4: patch: not found
  upcase
/bin/sh: 4: patch: not found
  v2_as
/bin/sh: 4: patch: not found
  vec0407
/bin/sh: 4: patch: not found
Makefile:87: recipe for target 'u0.s' failed
make[1]: *** [u0.s] Error 127
make[1]: Leaving directory '/root/Desktop/unix-master/build'
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qrush** [comment]
Closing all these as this is just an import/historical repo.
